// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 04.12.2025, 21:15:38
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/km929/Desktop/didar3/hakaton/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/km929/Desktop/didar3/hakaton/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/km929/Desktop/didar3/hakaton/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/km929/Desktop/didar3/hakaton/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/km929/Desktop/didar3/hakaton/plugins/**/*.{js,ts,mjs}","C:/Users/km929/Desktop/didar3/hakaton/composables/**/*.{js,ts,mjs}","C:/Users/km929/Desktop/didar3/hakaton/utils/**/*.{js,ts,mjs}","C:/Users/km929/Desktop/didar3/hakaton/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/km929/Desktop/didar3/hakaton/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/km929/Desktop/didar3/hakaton/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/km929/Desktop/didar3/hakaton/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;