// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 19.02.2026, 19:15:45
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/km929/Desktop/piaps/hakaton/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/km929/Desktop/piaps/hakaton/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/km929/Desktop/piaps/hakaton/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/km929/Desktop/piaps/hakaton/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/km929/Desktop/piaps/hakaton/plugins/**/*.{js,ts,mjs}","C:/Users/km929/Desktop/piaps/hakaton/composables/**/*.{js,ts,mjs}","C:/Users/km929/Desktop/piaps/hakaton/utils/**/*.{js,ts,mjs}","C:/Users/km929/Desktop/piaps/hakaton/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/km929/Desktop/piaps/hakaton/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/km929/Desktop/piaps/hakaton/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/km929/Desktop/piaps/hakaton/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;