// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 05.12.2025, 03:20:27
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["E:/repositories/hakaton/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/repositories/hakaton/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/repositories/hakaton/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/repositories/hakaton/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/repositories/hakaton/plugins/**/*.{js,ts,mjs}","E:/repositories/hakaton/composables/**/*.{js,ts,mjs}","E:/repositories/hakaton/utils/**/*.{js,ts,mjs}","E:/repositories/hakaton/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/repositories/hakaton/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/repositories/hakaton/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/repositories/hakaton/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;